name: Deploy VitePress to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm run docs:build

      - name: Deploy to Vercel
        run: |
          pnpm install -g vercel
          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} --yes \
            --confirm --cwd=.vitepress/dist